switch to github ci
mitodl/mitxpro-openedx-extensions pull request #10
Opened 2020-12-09 10:11 UTC by umarmughal824

Switch from travis to github ci

2020-12-10 16:19 UTC, rhysyngsun requested changes

2020-12-10 16:19 UTC, rhysyngsun commented on .github/workflows/ci.yml
> +        run: pip install Poetry
```suggestion
        run: pip install -Iv Poetry==1.1.4
```

2020-12-11 13:59 UTC, umarmughal824 commented
@rhysyngsun your feedback is addressed so that's ready for review again.

2020-12-14 14:22 UTC, rhysyngsun approved these changes

2020-12-14 17:08 UTC, merged